# RIPChest - Dartanman's DevRoom Application
MySQL:
  Host: 'localhost'
  Port: '3306'
  Database: 'schema'
  Username: 'admin'
  Password: 'password'
Settings:
  Death-Chest-Expire-Time-Seconds: 5
Messages:
  Need-Key-To-Open: '&cYou need a Death Key to open that!'