# RIPChest - Dartanman's DevRoom Application
MySQL:
  host: 'localhost'
  port: '3306'
  database: 'schema'
  username: 'admin'
  password: 'password'
Settings:
  Death-Chest-Expire-Time-Seconds: 600