# RIPChest - Dartanman's DevRoom Application
MySQL:
  Host: 'localhost'
  Port: '3306'
  Database: 'schema'
  Username: 'admin'
  Password: 'password'
Settings:
  Death-Chest-Expire-Time-Seconds: 5
  Player-Message-Interval-Seconds: 10
Messages:
  Need-Key-To-Open: '&cYou need a Death Key to open that!'
  Death-Chest-Despawning-Soon: '&cYour death chest expires in <seconds> seconds! You died at &eX: <x> Y: <y> Z: <z>'
  Death-Chest-Despawned-Or-Stolen: '&cYour death chest has despawned or been stolen!'